### ISSUE TITLE
Discord only allows nickname change of non-Administrators

### ISSUE THREAD

**Issue by Smephite** [Triton171/dsa-cli#2]
Discords permission system only allows changes of nicknames <= the bots rank and the user has not the rank Administrator.

Thus as soon as a user has the perk Administrator the Bot cannot change the nickname in `!in --all --rename/reset`.

We should implement a way a message is send instead so the user can its' name manually.

**Comment by Triton171** [comment]
The `!ini` command already returns a table with the initiative rolls for all characters.

From what I've tested, the Administrator permission does not prevent the bot from renaming someone, as long as the bot role is ranked above all of the other person's roles. The only limitation that cannot be fixed, is that the server owner can never be renamed.

Maybe we should add a section to the Readme on how to make `!ini -a --rename` work for (almost) everyone.

**Comment by Smephite** [comment]
Included in dc60279 #6
