### ISSUE TITLE
Use Discords 'Slash Commands'

### ISSUE THREAD

**Issue by Smephite** [Triton171/dsa-cli#3]
[Improvement]

Maybe use Slash Commands instead of the `!` prefix.

More info: 

https://discord.com/developers/docs/interactions/slash-commands

https://github.com/serenity-rs/serenity/tree/current/examples/e14_slash_commands

**Comment by Triton171** [comment]
That would be nice. Ideally, we could write a compatibility layer between the discord API and clap argument parsing:
- A function that takes a clap app definition and returns equivalent discord application commands
- A function that takes a discord interaction and outputs the corresponding clap `ArgMatches`

We first have to make sure that the discord API supports all the features we currently use. For example, i don't know if it supports arguments/flags that can appear in any order, some of which take values.

**Comment by Smephite** [comment]
It seems like [serenity](https://github.com/serenity-rs/serenity) is still working on implementing slash commands.

The implementation in their 10.0.5 release does not work for me and it is already clear that the API is still changing (already breaking changes pushed to their git repo).

I propose to wait a little while until this feature becomes a little more mature.

**Comment by Smephite** [comment]
It seems like I am bad at researching, I successfully implemented a simple slash command in 858a193.  
It seems like a simple invite for the discord bot is not enough when playing with slash commands.  
We now need OAuth2 Authentication.  I added an explanation to the ReadMe in 3a368d1
