### ISSUE TITLE
Allow multiple characters per discord account

### ISSUE THREAD

**Issue by Triton171** [Triton171/dsa-cli#8]
A possible implementation might be an optional `name` argument for the `upload` command.
Then, either each command could have an argument where you can specify the character name, or there could be a command to switch the currently "active" character.

**Comment by Smephite** [comment]
I'd rather support a variation of the second variant:
Per channel / server choice.  

The first character a user uploads is treated as their default one.  
If a user now wants to use a different character it can be changed via an command but only for the given channel / server.

One could even go further and add a third layer to this where a user can define a default character for each server but also a different character for each channel in that server.  
This idea is similar to [my proposed implementation](https://github.com/Triton171/dsa-cli/issues/9#issuecomment-834946916) of #9 so maybe there could be a shared code base?

**Comment by Triton171** [comment]
I'm not sure if it should be per-channel/per-server. One of the main reasons for having multiple characters (as far as I can see) would be for the DM to use the bot for NPCs. For that, you would need several characters in the same server/channel, so some sort of labelling system would be necessary.

Also, this feature should not add too much complexity for the user. Ideally, nothing changes for people using just one character, while anyone using this feature can do so without having to understand any complicated details on how exactly the bot manages these characters.
